package com.xy.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import com.xy.mybatis.pojo.TbCard;
import com.xy.mybatis.pojo.TbCardExample;

@Mapper
public interface TbCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_card
     *
     * @mbg.generated
     */
    int insert(TbCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_card
     *
     * @mbg.generated
     */
    int insertSelective(TbCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_card
     *
     * @mbg.generated
     */
    List<TbCard> selectByExample(TbCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_card
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbCard record, @Param("example") TbCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_card
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbCard record, @Param("example") TbCardExample example);

    List<TbCard> selectAll();
}