package dao;

import org.apache.ibatis.annotations.Param;
import pojo.TbCard;
import pojo.TbCardExample;

public interface TbCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_card
     *
     * @mbg.generated
     */
    int insert(TbCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_card
     *
     * @mbg.generated
     */
    int insertSelective(TbCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_card
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbCard record, @Param("example") TbCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_card
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbCard record, @Param("example") TbCardExample example);
}