package pojo;

public class TbCard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_card.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_card.card_style_id
     *
     * @mbg.generated
     */
    private Integer cardStyleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_card.card_param_value_json
     *
     * @mbg.generated
     */
    private String cardParamValueJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_card.id
     *
     * @return the value of tb_card.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_card.id
     *
     * @param id the value for tb_card.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_card.card_style_id
     *
     * @return the value of tb_card.card_style_id
     *
     * @mbg.generated
     */
    public Integer getCardStyleId() {
        return cardStyleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_card.card_style_id
     *
     * @param cardStyleId the value for tb_card.card_style_id
     *
     * @mbg.generated
     */
    public void setCardStyleId(Integer cardStyleId) {
        this.cardStyleId = cardStyleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_card.card_param_value_json
     *
     * @return the value of tb_card.card_param_value_json
     *
     * @mbg.generated
     */
    public String getCardParamValueJson() {
        return cardParamValueJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_card.card_param_value_json
     *
     * @param cardParamValueJson the value for tb_card.card_param_value_json
     *
     * @mbg.generated
     */
    public void setCardParamValueJson(String cardParamValueJson) {
        this.cardParamValueJson = cardParamValueJson == null ? null : cardParamValueJson.trim();
    }
}